spring.application.name=Samsung-Category-Service

server.port=8071

# MongoDB
spring.data.mongodb.uri=mongodb+srv://kumaryadavarvind1998_db_user:Arvind2314@mycluster1.owulczg.mongodb.net/samsung_db?retryWrites=true&w=majority


# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
